{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "celadon.database.name" . }}
  labels: {{- include "celadon.database.labels" . | nindent 4 }}
  annotations: {{- include "celadon.annotations" . | nindent 4 }}
data:
  02_create_tables.sql: |
    {{- required "helm/files/02_create_tables.sql is missing" (.Files.Get "files/02_create_tables.sql") | nindent 4 }}
{{- end }}
