[tool.poetry]
name = "celadon"
version = "0.1.0"
description = "API server for customer management"
authors = ["Peter Han <git@peterhan.ca>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^1.1.4"
gunicorn = "^20.0.4"
flask-cors = "^3.0.10"
psycopg2-binary = "^2.9.7"

[tool.poetry.group.dev.dependencies]
pycodestyle = "^2.11.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
