---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.config.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: application
spec:
  replicas: {{ .Values.hpa.minReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.config.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.config.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/component: application
    spec:
      containers:
        - name: {{ .Values.config.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: GUNICORN_CMD_ARGS
              value: {{ .Values.config.gunicornArgs }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.name }}-database
                  key: database_url
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
