---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "celadon.database.name" . }}
  labels: {{- include "celadon.database.labels" . | nindent 4 }}
  annotations: {{- include "celadon.annotations" . | nindent 4 }}
type: Opaque
data:
  {{- $host := .Values.connection.host | default (include "celadon.database.name" .) }}
  {{- $username := required "connection.username is required" .Values.connection.username }}
  {{- $password := required "connection.password is required" .Values.connection.password }}
  database_url: "{{ printf "postgres://%s:%s@%s:%s/%s" $username $password $host .Values.connection.port .Values.connection.dbName | b64enc }}"
  database_password: "{{ $password | b64enc }}"
  google_client_id: "{{ required "auth.googleClientId is required" .Values.auth.googleClientId | b64enc }}"
  google_client_secret: "{{ required "auth.googleClientSecret is required" .Values.auth.googleClientSecret | b64enc }}"
  flask_session_signing_key: "{{ required "auth.flaskSessionSigningKey is required" .Values.auth.flaskSessionSigningKey | b64enc }}"
