---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "celadon.database.name" . }}
  labels: {{- include "celadon.database.labels" . | nindent 4 }}
  annotations: {{- include "celadon.annotations" . | nindent 4 }}
type: Opaque
data:
  {{- $host := .Values.connection.host | default (include "celadon.database.name" .) }}
  database_url: "{{ printf "postgres://%s:%s@%s:%s/%s" .Values.connection.username .Values.connection.password $host .Values.connection.port .Values.connection.dbName | b64enc }}"
  database_password: "{{ .Values.connection.password | b64enc }}"
