apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  database_url: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.database.username .Values.database.password .Values.database.hostname  .Values.database.port .Values.database.dbName | b64enc | quote }}
  database_hostname: {{ .Values.database.hostname | b64enc | quote }}
  database_port: {{ .Values.database.port | b64enc | quote }}
  database_name: {{ .Values.database.dbName | b64enc | quote }}
  database_username: {{ .Values.database.username | b64enc | quote }}
  database_password: {{ .Values.database.password | b64enc | quote }}
