{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.name }}-postgres
  labels:
    app.kubernetes.io/name: {{ .Values.config.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: database
spec:
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.config.name }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
