{{- if .Values.application.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "celadon.application.name" . }}
  labels: {{- include "celadon.application.labels" . | nindent 4 }}
  annotations:
    {{- with merge (.Values.application.hpa.annotations | default dict) (include "celadon.annotations" . | fromYaml) }}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
spec:
  maxReplicas: {{ .Values.application.hpa.maxReplicas }}
  minReplicas: {{ .Values.application.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "celadon.application.name" . }}
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.application.hpa.avgMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.application.hpa.avgCPUUtilizationPercentage }}
{{- end }}
