name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry==1.6.1
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
      - name: Install dependencies
        run: poetry install --with dev --no-root
      - name: Lint
        run: poetry run pycodestyle
      - name: Test
        run: poetry run pytest

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
